CREATE CACHED TABLE public.author
(
	id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	lastname   VARCHAR(100) NOT NULL,
	middlename VARCHAR(100) NOT NULL,
	name       VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
);

CREATE CACHED TABLE public.genre
(
	id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	name VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
);

CREATE CACHED TABLE public.book
(
	id               BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	city             VARCHAR(100),
	name             VARCHAR(100) NOT NULL,
	publication_year DATE,
	publisher        VARCHAR(100),
	author_id        BIGINT NOT NULL,
	genre_id         BIGINT NOT NULL,
	CONSTRAINT book_author_id_fk FOREIGN KEY (author_id) REFERENCES public.author(id),
  CONSTRAINT book_genre_id_fk FOREIGN KEY (genre_id) REFERENCES public.genre(id),
  PRIMARY KEY (id)
);
