--INSERT DATA
INSERT INTO AUTHOR (ID, NAME, LASTNAME, MIDDLENAME) VALUES (1, 'Aleksandr', 'Pushkin', 'Sergeevich');
INSERT INTO AUTHOR (ID, NAME, LASTNAME, MIDDLENAME) VALUES (2, 'Aleksandr2', 'Pushkin2', 'Sergeevich2');
INSERT INTO GENRE (ID, NAME) VALUES (1, 'Novel');
INSERT INTO BOOK (ID, NAME, AUTHOR_ID, GENRE_ID, PUBLISHER, PUBLICATION_YEAR, CITY) VALUES (1, 'The Tale of Tsar Saltan', 1, 1, 'OOO "PrintStudio"', '2018-10-21', 'Moscow');